pool: Default
jobs:
- job: sast_scan
  steps:
  - script: bandit -f json -o Reports/sast-result.json -r app/app.py || true
  - task: CopyFiles@2
    inputs:
      sourceFolder: './Reports'
      contents: '*.json'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: sast_results

- job: sca_scan
  steps:
  - script: pyraider check -f app/requirements.txt -e json Reports/sca-results.json || true
  - task: CopyFiles@2
    inputs:
      sourceFolder: './Reports'
      contents: '*.json'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: sca_results